clean: true
sdk: iphonesimulator
xcodebuild_arguments:
 - -workspace
 - VerIDSerialization.xcworkspace
 - -scheme
 - VerIDSerialization
 - -sdk
 - iphonesimulator
 - -arch
 - x86_64
author: Applied Recognition, Inc.
module: VerIDSerialization
min_acl: public
