// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: system_info.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Verid_SystemInfo {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var deviceInfo: Verid_DeviceInfo {
    get {return _deviceInfo ?? Verid_DeviceInfo()}
    set {_deviceInfo = newValue}
  }
  /// Returns true if `deviceInfo` has been explicitly set.
  var hasDeviceInfo: Bool {return self._deviceInfo != nil}
  /// Clears the value of `deviceInfo`. Subsequent reads from it will return its default value.
  mutating func clearDeviceInfo() {self._deviceInfo = nil}

  var veridVersion: String = String()

  var veridSettings: Verid_VerIDSettings {
    get {return _veridSettings ?? Verid_VerIDSettings()}
    set {_veridSettings = newValue}
  }
  /// Returns true if `veridSettings` has been explicitly set.
  var hasVeridSettings: Bool {return self._veridSettings != nil}
  /// Clears the value of `veridSettings`. Subsequent reads from it will return its default value.
  mutating func clearVeridSettings() {self._veridSettings = nil}

  var faceDetectionClassName: String = String()

  var faceRecognitionClassName: String = String()

  var userManagementClassName: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _deviceInfo: Verid_DeviceInfo? = nil
  fileprivate var _veridSettings: Verid_VerIDSettings? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Verid_SystemInfo: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "verid"

extension Verid_SystemInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SystemInfo"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "device_info"),
    2: .standard(proto: "verid_version"),
    3: .standard(proto: "verid_settings"),
    4: .standard(proto: "face_detection_class_name"),
    5: .standard(proto: "face_recognition_class_name"),
    6: .standard(proto: "user_management_class_name"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._deviceInfo) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.veridVersion) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._veridSettings) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.faceDetectionClassName) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.faceRecognitionClassName) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.userManagementClassName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._deviceInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.veridVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.veridVersion, fieldNumber: 2)
    }
    try { if let v = self._veridSettings {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.faceDetectionClassName.isEmpty {
      try visitor.visitSingularStringField(value: self.faceDetectionClassName, fieldNumber: 4)
    }
    if !self.faceRecognitionClassName.isEmpty {
      try visitor.visitSingularStringField(value: self.faceRecognitionClassName, fieldNumber: 5)
    }
    if !self.userManagementClassName.isEmpty {
      try visitor.visitSingularStringField(value: self.userManagementClassName, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Verid_SystemInfo, rhs: Verid_SystemInfo) -> Bool {
    if lhs._deviceInfo != rhs._deviceInfo {return false}
    if lhs.veridVersion != rhs.veridVersion {return false}
    if lhs._veridSettings != rhs._veridSettings {return false}
    if lhs.faceDetectionClassName != rhs.faceDetectionClassName {return false}
    if lhs.faceRecognitionClassName != rhs.faceRecognitionClassName {return false}
    if lhs.userManagementClassName != rhs.userManagementClassName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
